### PR TITLE
complete readme rewrite

### PR DESCRIPTION
**Pull request by joskezelensky**

### CODE REVIEW

**Comment by maforget** [comment]
You've removed the link to the zip version, this should stay. Also I am not certain of the download button just sending it lower for the real download link. We need to think of the lowest common denominator. Github can be very confusing for some people, it should be super obvious where the download link is. That is why I put them on the very top.

As for removing the upgrading instructions, these should be there also. It's going to be the #1 question for people transferring from ComicRack, and like I stated above it should be very obvious without the need to go find an article in the Wiki or some stuff.

For the Android Link, the Pack or Keygen isn't required anymore, but it does contain the link to the APK. I would just link to the APK directly instead. Maybe put a link for the Android wiki instructions.

**Comment by joskezelensky** [comment]
> You've removed the link to the zip version, this should stay. Also I am not certain of the download button just sending it lower for the real download link. We need to think of the lowest common denominator. Github can be very confusing for some people, it should be super obvious where the download link is. That is why I put them on the very top.
> 
> As for removing the upgrading instructions, these should be there also. It's going to be the #1 question for people transferring from ComicRack, and like I stated above it should be very obvious without the need to go find an article in the Wiki or some stuff.
> 
> For the Android Link, the Pack or Keygen isn't required anymore, but it does contain the link to the APK. I would just link to the APK directly instead. Maybe put a link for the Android wiki instructions.

it was mostly the confusing big texts, and it wasn't easy to know what the repo was about at a glance. It's true that the **downloads should be kept at the top**, but at least a bit more **formatting** was meant with this commit

**Comment by maforget** [comment]
Can you change it?

**Comment by joskezelensky** [comment]
> Can you change it?

wdym?

**Comment by maforget** [comment]
Can you fix the readme with the requested changes so I can merge it?

**Comment by joskezelensky** [comment]
> Can you fix the readme with the requested changes so I can merge it?

i need to study for my exams, will do when i have spare time.

**Pull request merged**
