### PR TITLE
New updated icons6

### PR DESCRIPTION
**Pull request by ucapato**
Update on Globo and DC Comics logo in addition the Brand change throughout time

### CODE REVIEW

**Comment by maforget** [comment]
You really need to update your branches more before doing a merge. Like I stated in #62, the folder has changed location.

**Comment by ucapato** [comment]
> You really need to update your branches more before doing a merge. Like I stated in #62, the folder has changed location.

Yes, I have seen your latest change with the Output Directory, but I have done something wrong at my Fork that never synch this latest updated. I double-check that in a next update.

**Comment by maforget** [comment]
Your online commits seems fine, what is probably happening is that locally you are reusing the same branch name `NewUpdatedIcons6`. You've deleted the Github branch in the last PR, but you probably kept the offline version and that was the one that was checked out. You added the files to it without realizing that the version you had was based on your old PR. Pushed it and it was based on the old PR.

Not a big deal, this is why git is useful, I wasn't sure myself how it would react to different folders. In fact is detected the folder moves even for new files 😀. It's bound to happen, I've got several branches that are pretty old.

One thing to keep in mind I've discovered. Once things have been pushed to Github you don't want to mess with the commit history by doing a rebase or a force push for example.

**Comment by ucapato** [comment]
Ok, I see...

My practice today after a PR and having it merged is to always delete the latest used branch (e.g.: NewUpdatedIcons6) and create a new one (e.g.: NewUpdatedIcons7) at my forked repo. As I have new updates I'll "populate" this branch until I feel it is time to make a new PR. Git is a bit confusing sometimes, but it has some beauty on it as well.

**Comment by maforget** [comment]
Deleting the old branch is fine, but remember that not only the one from GitHub but that same branch locally also. 

And to make sure which is the one that is currently checked out when pushing changes.

**Pull request merged**
