### PR TITLE
Installer configuration

### PR DESCRIPTION
**Pull request by Totengeist**
Here is a mostly functional installer script utilizing NSIS and ComicRack's original setup script. There are some issues to resolve and a few questions to answer.

**Notes:**
* The [ExecDos plugin](https://nsis.sourceforge.io/ExecDos_plug-in) for NSIS is required.
* I upgraded from NSIS 2.46 to NSIS 3.09, but it should work with both.
* The installer looks different. I think cYo used some plugins that I haven't identified.
* The original installer mentioned the version number *every* time it said "ComicRack" somewhere. I've reduced that.
* `modern-wizard.bmp` is missing. I was able to extract it from the original installer, but it might not be royalty-free.

**Issues/questions:**
* The "welcome page" is blank.
* Uninstall doesn't work. This appears to have been missing from the original file listed in #5.
* I haven't resolved an error on the Component Selection screen, so it is temporarily disabled.
* Should we change the installation directory to "ComicRack Community Edition"?

### CODE REVIEW

**Comment by maforget** [comment]
I have 0 experience with NSIS, so I will trust your expertise. I didn't expect to be able to use the script as is. I taught most was junk. 

**Here are some remarks:**
* You stated that you changed it so that the version info doesn't repeat, there seems to be a lot of repeat still. Any way so that we can change it once in a variable and it get distributed through out.
* This is based on the .NET Framework 4.8, we should update the link about it. If some user have a windows version older, it might not be pre installed. It looks like there is some kind of detection in the installer if it's not already installed. By checking the [default installation of 4.8 in Windows](https://learn.microsoft.com/en-us/dotnet/framework/migration-guide/versions-and-dependencies#net-framework-48), even some variation of Windows 10 don't have it. And we know some still use windows 7.
* Can we automate the file list at all? Some files have been removed like LinqToTwitter, but are still there (you should update your master before doing a fork, you will probably need to do a rebase). A lot were added (that are missing) just by updating the libraries and you didn't see the quantity that were added while I was testing new PDF libraries. This is bound to be updated even more by changing and updating stuff like the OpenGL library. Everything in the Release folder should be included. We shouldn't have to update the script continuously for each change.
* We can have scripts that are run after the build, in the post-build event. Like I said my knowledge is limited, but my guess is that we could have script that will fill the install script itself, like files or version number.
* Keep in mind that this will be build by Github, so we will need to make certain that the components needed are available to be installed as github workflows. If not it will need to be scripted, either in the workflow file or a batch file that will be called after it is build. My workflow would be to go to the release action in Github and run the workflow, enter the version number (or other variable) and it will create a release with the file linked.
* Don't be afraid to update your framework or tooling instead of trying to keep the script intact and keeping old versions. 

**Answer to your questions:**
* Yes, I would change the path to include ComicRack Community Edition, we don't want to touch existing installs
* Here is the image I used to do the splash screen, you could use part to include in the installer.
* We could remove the component selection and install all ressources like textures, languages, but some people will like to disable start menu and the such.
* We will need to create an uninstaller. I was guessing that it was pretty much created automatically when doing the installer (the ones I tried did).

**Comment by Totengeist** [comment]
Thanks for the feedback! This is my first time working on an existing project, so the feedback is very helpful.

>     * You stated that you changed it so that the version info doesn't repeat, there seems to be a lot of repeat still. Any way so that we can change it once in a variable and it get distributed through out.
> 
>     * Can we automate the file list at all? Some files have been removed like LinqToTwitter, but are still there (you should update your master before doing a fork, you will probably need to do a rebase). A lot were added (that are missing) just by updating the libraries and you didn't see the quantity that were added while I was testing new PDF libraries. This is bound to be updated even more by changing and updating stuff like the OpenGL library. Everything in the Release folder should be included. We shouldn't have to update the script continuously for each change.

I already converted the version number to a variable and removed LinqToTwitter. Are you only looking at the first commit? I'll look into loading files automatically. I know Inno Setup can do that and I can't imagine NSIS not having that, too.

>     * We can have scripts that are run after the build, in the post-build event. Like I said my knowledge is limited, but my guess is that we could have script that will fill the install script itself, like files or version number.

I was going to look into doing that once I've figured everything else out. I've done this in Python. We should be able to do something similar with batch files or something.
 
>     * Keep in mind that this will be build by Github, so we will need to make certain that the components needed are available to be installed as github workflows. If not it will need to be scripted, either in the workflow file or a batch file that will be called after it is build. My workflow would be to go to the release action in Github and run the workflow, enter the version number (or other variable) and it will create a release with the file linked.
> 
>     * Don't be afraid to update your framework or tooling instead of trying to keep the script intact and keeping old versions.
> 
>     * We could remove the component selection and install all ressources like textures, languages, but some people will like to disable start menu and the such.
> 
>     * We will need to create an uninstaller. I was guessing that it was pretty much created automatically when doing the installer (the ones I tried did).

I may end up switching to Inno Setup if I can't get it working properly in NSIS. Inno Setup does the uninstaller automatically, and I figured NSIS would do this, too. We can always switch back in the future if we need to.

**Comment by maforget** [comment]
I've looked into the Visual Studio Installer and honestly it looks way easier. The files and dependencies get auto filled, set file associations.

**Comment by Totengeist** [comment]
I hadn't heard of that. I'll look at that tomorrow!

**Comment by Totengeist** [comment]
This update works, but there's an issue with the workflows. You can't use `with` when you're using `runs-on`, but I haven't figured out how to resolve it yet.

**Comment by Totengeist** [comment]
I switched from NSIS to Inno Setup. I looked at Visual Studio Installer, but many people said MSIs had more problems with difficult-to-track-down errors. The installer is similar to the previous ComicRack one and has all the same options except for optimizing.

Let me know if there's anything you feel needs changing. I ran the nightly workflow on my repo and it seemed to work fine.

**Comment by maforget** [comment]
Looks good, a lot more readable. I believe we should have at least the file association, since for "those" people, it's one of the prime reason, like for installing plugins would be worse. For the SupportedTypes, you are using the wrong type, I don't see a lot of program using it, but it's in the MS Documentation wouldn't hurt. You need to also add the App Path. 

For the Setup Icon you should use the **"uninst_103.ico"**, it's the original installation icon.

Did you create the file yourself or did you use a tool, if so which one?

For the File Association (I've attached a reg file with all the changes I could think of):
[ComicRack.reg.txt](https://github.com/maforget/ComicRackCE/files/14047067/ComicRack.reg.txt)

**For Comics (.cbz, .cbt, .cbr. cb7, .cbw)**
Name: cYo.ComicRack
Description: eComic
Icon is the second icon (it should be the second one ,1)
open => Open eComic with ComicRack
open command => "%1"

**For the list**
Name: cYo.ComicList
Description: eComic List
Icon should be the 3rd one (,2)
open => Open eComic with ComicRack
open command => -il "%1"

**For the plugin**
Name: cYo.ComicRackPlugin
Description: eComic List
Icon should be the last one (,3)
open => Install Plugin into ComicRack
open command => -ip "%1"

**Comment by maforget** [comment]
Also the Help & Script folder are missing,

**Comment by Totengeist** [comment]
Thanks. As I've been thinking more about it, I've realized a few things I missed. Will continue to work on it. I thought I'd done a file comparison, but I think that was the old NSIS installer setup.

**Comment by Totengeist** [comment]
I think the last main issue to resolve now is .NET Framework check and download. I've found the information I need. It'll just take me a bit to get it working and I'll need to set up a VM without .NET Framework 4.8 to verify.

**Comment by maforget** [comment]
You used with the import & Install plugin _ComicRack CE_, but not with the eComic "Open eComic with ComicRack". Let's be consistent.

Shouldn't the associate lines have a `Components: associate` if the persons chooses to not associate?

When I tested the other version it permitted to install without Admin access, what would happen if it was required to install the .NET Framework in that case, since that would need Admin access. Would it prompt for it automatically and failing if not given access?

**Comment by Totengeist** [comment]
> When I tested the other version it permitted to install without Admin access, what would happen if it was required to install the .NET Framework in that case, since that would need Admin access. Would it prompt for it automatically and failing if not given access?

This happens when it is already installed. If you uninstall first, that option will come back. Since the .NET install has it's own installer, it should elevate itself. I'll test this in my VM once I can set it up. I'll fix the consistency issue and the association option.

**Comment by maforget** [comment]
I agree that we should keep the Open With functionality. Pretty much anything that is in the Application specific section should stay. But I think we should add the correct icon to the default open action so that if we do Open with later, the correct icon would be there.

`Root: HKA; Subkey: "Software\Classes\Applications\{#MyAppExeName}\DefaultIcon";    ValueType: string; Flags: uninsdeletevalue; ValueData: """{autopf}\{#MyAppName}\{#MyAppExeName}"",1"`

We should also remove the `.cbl` & `.crplugin` from the SupportedTypes since they won't work with the default open command.

Also how did you have _ComicRack Community Edition_ shown in the open with window, I tested your last setup and it only gives _ComicRack_. Did you add something else? I was looking at how the FriendlyAppName worked to fix that. Since there is no details in the exe, I am guessing is the problem. I will have to check to add at least some info in the .res file.

**Comment by maforget** [comment]
Yeah I've tested with adding this reg value and it shown the app name correctly.

```
[HKEY_LOCAL_MACHINE\Software\Classes\Applications\ComicRack.exe]
"FriendlyAppName"="ComicRack Community Edition"
```

**Comment by Totengeist** [comment]
> Yeah I've tested with adding this reg value and it shown the app name correctly.
> 
> ```
> [HKEY_LOCAL_MACHINE\Software\Classes\Applications\ComicRack.exe]
> "FriendlyAppName"="ComicRack Community Edition"
> ```

Yeah, I have that in a local commit. I hadn't pushed it yet since I wanted to wait for your answer.

**Comment by Totengeist** [comment]
I also found information about signing the installers that might work with the workflows. I need to do some testing to verify.

**Comment by maforget** [comment]
Wouldn't that need a certificate that costs hundreds of dollars per year?

**Comment by Totengeist** [comment]
Yeah, apparently it does now. I didn't realize they require Organization Validation now. Nevermind.

**Comment by maforget** [comment]
I've changed back the installer to the original type so it overrides them. The problem is that it sometimes writes the association in the HKCU, when you close the Preferences dialog (I believe if it exists already). So even when installing the new program it still opens with the OG ComicRack. That way it will override the default open command and the existing HKCU association will open the new one even if set to cYo.ComicRack.

I still have the problem is that the OG ComicRack calls himself ComicRack Community Edition in the OPen With, because we added the FriendlyAppName for ComicRack.exe. Might need to rename the exe itself to something else.

**Comment by Totengeist** [comment]
Yeah, unfortunately the registry references everything by the filename and not the path or some other unique identifier. I wasn't sure how difficult changing the executable filename would be, so I left it. I didn't want to break anything by accident.

**Pull request merged**
